version: 0.0

os: linux
files:
  - source: /
    destination: /home/ubuntu/AWS_ECDjangoDeployer
permissions:
  - object: /home/ubuntu/AWS_ECDjangoDeployer
    owner: ubuntu
    group: ubuntu
#
hooks:
  BeforeInstall:
    - location: CodeDeploy/BeforeInstall.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: CodeDeploy/AfterInstall.sh
      timeout: 300
      runas: ubuntu
  ApplicationStop:
    - location: CodeDeploy/ApplicationStop.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: CodeDeploy/ApplicationStart.sh
      timeout: 300
      runas: ubuntu
